-- Seed Questions (100 Existential Questions)
INSERT INTO public.questions (text, category) VALUES
('If you had only one year left, what would you stop postponing today?', 'existential'),
('What dream dies with you if you never start?', 'existential'),
('Who will remember your name in fifty years?', 'legacy'),
('What are you sacrificing your life for?', 'purpose'),
('If today were your final ordinary day, would you be proud of how you lived?', 'existential'),
('What truth are you avoiding because the answer requires radical change?', 'truth'),
('Who do you need to forgive before time runs out?', 'forgiveness'),
('If you could give one message to your future self, what would it be?', 'reflection'),
('What part of yourself are you pretending to be?', 'identity'),
('What would you do today if you knew fear was only an illusion?', 'courage'),
('If your life was a movie, would anyone want to watch this chapter?', 'action'),
('What legacy are you building in the silence of your daily habits?', 'legacy'),
('What relationship are you starving while chasing temporary distraction?', 'relationships'),
('If you were stripped of your titles, wealth, and status, who remains?', 'identity'),
('What conversation have you delayed out of cowardice?', 'courage'),
('What would you create if you cared nothing about applause?', 'purpose'),
('Are you living out your own destiny, or fulfilling someone else''s expectations?', 'identity'),
('What painful truth are you masking with busywork?', 'truth'),
('How much of your day was spent living rather than merely surviving?', 'time'),
('If you were to die tonight, what would be your greatest regret?', 'regret'),
('What noise in your life must you quiet to hear your true calling?', 'peace'),
('What gift are you withholding from the world out of self-doubt?', 'purpose'),
('Who would you call right now if you knew it was your last phone call?', 'relationships'),
('Is your current path leading to the person you wish to become?', 'destiny'),
('What compromise are you making that quietly destroys your soul?', 'integrity'),
('What are you holding onto that you need to let go?', 'release'),
('When was the last time you felt truly, deeply alive?', 'presence'),
('If you had $100M but only 6 months to live, how would you spend your time?', 'value'),
('What mask are you wearing that has grown too heavy?', 'identity'),
('What habit must die so that your highest self can live?', 'growth'),
('Whose approval are you still chasing from your childhood?', 'freedom'),
('If you were guaranteed failure, would you still attempt it for the joy of trying?', 'passion'),
('How many days of your life have you surrendered to worry?', 'time'),
('What beauty did you walk past today without noticing?', 'presence'),
('What unexpressed gratitude is waiting in your heart?', 'gratitude'),
('Are you building a life or building a resume?', 'purpose'),
('If your time is money, what are you buying with your hours?', 'value'),
('What fear is keeping you from total honesty with yourself?', 'truth'),
('What promise to yourself have you repeatedly broken?', 'integrity'),
('What would you say at your own funeral?', 'legacy'),
('Are you choosing comfort over growth?', 'courage'),
('What small action today will your future self thank you for?', 'action'),
('Whose life is measurably better because you existed?', 'legacy'),
('What grudge are you nursing that poisons only you?', 'forgiveness'),
('If you knew the exact date of your death, how would your schedule change tomorrow?', 'time'),
('What part of your life requires courage right now?', 'courage'),
('What are you doing today that will matter in ten years?', 'legacy'),
('If you lost everything tomorrow, what inner strength would sustain you?', 'resilience'),
('What secret wish are you waiting for permission to fulfill?', 'desire'),
('Who needs your kindness today more than you need your pride?', 'kindness'),
('What work would you do even if you were never paid for it?', 'passion'),
('How much of your identity is tied to opinions of people you don''t even respect?', 'freedom'),
('What question are you afraid to ask yourself?', 'truth'),
('What part of your day gave you peace?', 'peace'),
('Are you present in your own story, or watching it pass by?', 'presence'),
('What would your 80-year-old self tell your current self?', 'wisdom'),
('What would your 8-year-old self think of who you have become?', 'identity'),
('What boundary do you need to set to protect your peace?', 'self-care'),
('What lie are you telling yourself to stay comfortable?', 'truth'),
('How often do you listen to understand rather than to reply?', 'relationships'),
('What armor can you drop today?', 'vulnerability'),
('What is the heaviest burden you carry that isn''t yours?', 'freedom'),
('If you could undo one choice, would you trade the lesson it taught you?', 'wisdom'),
('What simple pleasure did you take for granted today?', 'gratitude'),
('Who brings out the highest version of you?', 'relationships'),
('What environment are you tolerating that drains your energy?', 'peace'),
('Are you reacting to life or actively creating it?', 'agency'),
('What act of love can you perform anonymously today?', 'kindness'),
('What skill or wisdom will you leave behind?', 'legacy'),
('How much longer will you wait for the ''right time''?', 'action'),
('What truth feels dangerous to speak aloud?', 'courage'),
('What are you consuming that is poisoning your mind?', 'mindfulness'),
('If you lost your sight tomorrow, what would you miss seeing most?', 'gratitude'),
('What part of your past are you allowing to dictate your future?', 'freedom'),
('Are you treating time as infinite or sacred?', 'memento-mori'),
('What would change if you gave 100% devotion to your current task?', 'focus'),
('Who needs to hear ''I love you'' before it''s too late?', 'relationships'),
('What price are you paying for your silent compliance?', 'integrity'),
('What is something you love doing that you haven''t done in years?', 'joy'),
('If your thoughts were broadcast to the world, would you be proud?', 'mindfulness'),
('What anchor is holding your ship in the harbor?', 'courage'),
('Are you cultivating wisdom or hoarding information?', 'wisdom'),
('What apology do you owe to yourself?', 'forgiveness'),
('How do you want to be remembered by those closest to you?', 'legacy'),
('What simple truth did you learn the hard way?', 'wisdom'),
('What noise can you eliminate from your routine today?', 'peace'),
('If this year were your entire life condensed, how was it lived?', 'memento-mori'),
('What act of self-care have you denied yourself?', 'self-care'),
('Whose standard of success are you measuring yourself against?', 'identity'),
('What are you resisting that is trying to teach you?', 'wisdom'),
('What makes your heart burn with purpose?', 'purpose'),
('If you could master one virtue this year, which would it be?', 'virtue'),
('What is standing between you and complete authenticity?', 'truth'),
('How many precious moments have you traded for screen time?', 'time'),
('What is the most meaningful risk you haven''t taken yet?', 'courage'),
('Whose life could you transform with one courageous decision?', 'impact'),
('What heavy expectation can you put down right now?', 'freedom'),
('Are you accumulating possessions or accumulating experiences?', 'wisdom'),
('If death is certain, why hesitate to live fully?', 'memento-mori'),
('What single choice today would align you with your highest purpose?', 'purpose');

-- Seed Quotes (100 Stoic & Existential Quotes)
INSERT INTO public.quotes (quote, author, source) VALUES
('You could leave life right now. Let that determine what you do and say and think.', 'Marcus Aurelius', 'Meditations'),
('It is not that we have a short time to live, but that we waste a lot of it.', 'Seneca', 'On the Shortness of Life'),
('He who has a why to live can bear almost any how.', 'Friedrich Nietzsche', 'Twilight of the Idols'),
('No man is happy who does not think himself so.', 'Publilius Syrus', 'Moral Sayings'),
('Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose.', 'Steve Jobs', 'Stanford Commencement Address'),
('When we are no longer able to change a situation, we are challenged to change ourselves.', 'Viktor Frankl', 'Man''s Search for Meaning'),
('If you are living for the future, you are missing the only life you have.', 'Naval Ravikant', 'The Almanack of Naval Ravikant'),
('Don''t explain your philosophy. Embody it.', 'Epictetus', 'Enchiridion'),
('To live is the rarest thing in the world. Most people exist, that is all.', 'Oscar Wilde', 'The Soul of Man under Socialism'),
('Waste no more time arguing about what a good man should be. Be one.', 'Marcus Aurelius', 'Meditations'),
('Life is long if you know how to use it.', 'Seneca', 'On the Shortness of Life'),
('He who fights with monsters should look to it that he himself does not become a monster.', 'Friedrich Nietzsche', 'Beyond Good and Evil'),
('Wealth consists not in having great possessions, but in having few wants.', 'Epictetus', 'Discourses'),
('Your time is limited, so don''t waste it living someone else''s life.', 'Steve Jobs', 'Stanford Commencement Address'),
('Between stimulus and response there is a space. In that space is our power to choose our response.', 'Viktor Frankl', 'Man''s Search for Meaning'),
('Desire is a contract that you make with yourself to be unhappy until you get what you want.', 'Naval Ravikant', 'The Almanack of Naval Ravikant'),
('It is quality rather than quantity that matters.', 'Lucius Annaeus Seneca', 'Epistles'),
('Death smiles at us all, but all a man can do is smile back.', 'Marcus Aurelius', 'Meditations'),
('He who fears death will never do anything worthy of a man who is alive.', 'Seneca', 'Letters from a Stoic'),
('Amor Fati - Love your fate, which is in fact your life.', 'Friedrich Nietzsche', 'Ecce Homo'),
('First say to yourself what you would be; and then do what you have to do.', 'Epictetus', 'Discourses'),
('The only way to do great work is to love what you do.', 'Steve Jobs', 'Stanford Commencement Address'),
('Everything can be taken from a man but one thing: the last of the human freedoms—to choose one''s attitude.', 'Viktor Frankl', 'Man''s Search for Meaning'),
('A fit body, a calm mind, a house full of love. These things cannot be bought – they must be earned.', 'Naval Ravikant', 'The Almanack of Naval Ravikant'),
('He suffers more than necessary, who suffers before it is necessary.', 'Seneca', 'Letters from a Stoic'),
('The happiness of your life depends upon the quality of your thoughts.', 'Marcus Aurelius', 'Meditations'),
('I have lived through a lot of terrible things in my life, some of which actually happened.', 'Michel de Montaigne', 'Essays'),
('No man is free who is not master of himself.', 'Epictetus', 'Discourses'),
('Have the courage to follow your heart and intuition.', 'Steve Jobs', 'Stanford Commencement Address'),
('Those who have a ''why'' to live, can bear with almost any ''how''.', 'Viktor Frankl', 'Man''s Search for Meaning'),
('Peace is happiness at rest, and happiness is peace in motion.', 'Naval Ravikant', 'The Almanack of Naval Ravikant'),
('We suffer more often in imagination than in reality.', 'Seneca', 'Letters from a Stoic'),
('Dwell on the beauty of life. Watch the stars, and see yourself running with them.', 'Marcus Aurelius', 'Meditations'),
('What does not kill me makes me stronger.', 'Friedrich Nietzsche', 'Twilight of the Idols'),
('If you want to improve, be content to be thought foolish and stupid.', 'Epictetus', 'Enchiridion'),
('Stay hungry, stay foolish.', 'Steve Jobs', 'Whole Earth Catalog'),
('Forces beyond your control can take away everything you possess except one thing: your freedom to choose how you respond.', 'Viktor Frankl', 'Man''s Search for Meaning'),
('If you don''t own your time, you''ll never own your life.', 'Naval Ravikant', 'Tweets'),
('Begin at once to live, and count each separate day as a separate life.', 'Seneca', 'Letters from a Stoic'),
('Accept the things to which fate binds you, and love the people with whom fate brings you together.', 'Marcus Aurelius', 'Meditations'),
('The individual has always had to struggle to keep from being overwhelmed by the tribe.', 'Friedrich Nietzsche', 'Untimely Meditations'),
('Difficulties show what men are.', 'Epictetus', 'Discourses'),
('Details matter, it''s worth waiting to get it right.', 'Steve Jobs', 'Biography'),
('In some ways suffering ceases to be suffering at the moment it finds a meaning.', 'Viktor Frankl', 'Man''s Search for Meaning'),
('Clear thinking requires courage rather than intelligence.', 'Naval Ravikant', 'The Almanack of Naval Ravikant'),
('Luck is what happens when preparation meets opportunity.', 'Seneca', 'Letters from a Stoic'),
('The soul becomes dyed with the color of its thoughts.', 'Marcus Aurelius', 'Meditations'),
('There are no facts, only interpretations.', 'Friedrich Nietzsche', 'Notebooks'),
('Only the educated are free.', 'Epictetus', 'Discourses'),
('Innovation distinguishes between a leader and a follower.', 'Steve Jobs', 'The Innovation Secrets of Steve Jobs'),
('Self-actualization is impossible if it is made an end in itself.', 'Viktor Frankl', 'The Will to Meaning'),
('Impatience with actions, patience with results.', 'Naval Ravikant', 'Tweets'),
('As long as you live, keep learning how to live.', 'Seneca', 'Letters from a Stoic'),
('The best revenge is to be unlike him who performed the injury.', 'Marcus Aurelius', 'Meditations'),
('You must have chaos within you to give birth to a dancing star.', 'Friedrich Nietzsche', 'Thus Spoke Zarathustra'),
('Attach yourself to what is spiritually superior, regardless of what other people think or do.', 'Epictetus', 'Enchiridion'),
('Be a yardstick of quality. Some people aren''t used to an environment where excellence is expected.', 'Steve Jobs', 'Biography'),
('What is to give light must endure burning.', 'Viktor Frankl', 'Doctor and the Soul'),
('Wisdom is knowing the long-term consequences of your actions.', 'Naval Ravikant', 'The Almanack of Naval Ravikant'),
('While we wait for life, life passes.', 'Seneca', 'Letters from a Stoic'),
('Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.', 'Marcus Aurelius', 'Meditations'),
('The secret of reaping the greatest fruitfulness and the greatest enjoyment from existence is to live dangerously!', 'Friedrich Nietzsche', 'The Gay Science'),
('Silence is a lesson learned through the many sufferings of life.', 'Seneca', 'Thyestes'),
('Make the best use of what is in your power, and take the rest as it happens.', 'Epictetus', 'Discourses'),
('My favorite things in life don''t cost any money. It''s really clear that the most precious resource we all have is time.', 'Steve Jobs', 'Playboy Interview'),
('Fear makes come true that which one fears.', 'Viktor Frankl', 'The Doctor and the Soul'),
('If you can''t see yourself working with someone for life, don''t work with them for a day.', 'Naval Ravikant', 'The Almanack of Naval Ravikant'),
('To be everywhere is to be nowhere.', 'Seneca', 'Letters from a Stoic'),
('When you arise in the morning think of what a privilege it is to be alive, to think, to enjoy, to love.', 'Marcus Aurelius', 'Meditations'),
('He who has a why can bear almost any how.', 'Friedrich Nietzsche', 'Twilight of the Idols'),
('Man is not worried by real problems so much as by his imagined anxieties about real problems.', 'Epictetus', 'Enchiridion'),
('We don''t get a chance to do that many things, and every one should be really excellent.', 'Steve Jobs', 'Interview'),
('The last of human freedoms is to choose one''s attitude in any given set of circumstances.', 'Viktor Frankl', 'Man''s Search for Meaning'),
('Happiness is a state where nothing is missing.', 'Naval Ravikant', 'The Almanack of Naval Ravikant'),
('All cruelty springs from weakness.', 'Seneca', 'Letters from a Stoic'),
('Look back over the past, with its changing empires that rose and fell, and you can foresee the future, too.', 'Marcus Aurelius', 'Meditations'),
('Shared joys make a double joy as a shared sorrow makes a half a sorrow.', 'Swedish Proverb', 'Traditional'),
('Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.', 'Epictetus', 'Discourses'),
('I want to put a ding in the universe.', 'Steve Jobs', 'Biography'),
('An abnormal reaction to an abnormal situation is normal behavior.', 'Viktor Frankl', 'Man''s Search for Meaning'),
('The modern struggle is people trying to adapt to environments they weren''t designed for.', 'Naval Ravikant', 'Tweets'),
('If one does not know which port one is sailing to, no wind is favorable.', 'Seneca', 'Letters from a Stoic'),
('Loss is nothing else but change, and change is Natures delight.', 'Marcus Aurelius', 'Meditations'),
('The essence of all beautiful art, all great art, is gratitude.', 'Friedrich Nietzsche', 'Human, All Too Human'),
('Know, first, who you are; and then adorn yourself accordingly.', 'Epictetus', 'Discourses'),
('Design is not just what it looks like and feels like. Design is how it works.', 'Steve Jobs', 'NYT Magazine'),
('Ever more people have the means to live, but no meaning to live for.', 'Viktor Frankl', 'The Unheard Cry for Meaning'),
('If you don''t know what to do, do nothing. It''s better to do nothing than to do something wrong.', 'Naval Ravikant', 'The Almanack of Naval Ravikant'),
('Every night before going to sleep, we must ask ourselves: what weakness did I overcome today?', 'Seneca', 'On Anger'),
('The best answer to anger is silence.', 'Marcus Aurelius', 'Meditations'),
('That which is done out of love always takes place beyond good and evil.', 'Friedrich Nietzsche', 'Beyond Good and Evil'),
('Any person capable of angering you becomes your master.', 'Epictetus', 'Enchiridion'),
('The heavy burden of life is alleviated when we find meaning in our everyday existence.', 'Steve Jobs', 'Reflections'),
('Chasing happiness is the surest way to miss it.', 'Viktor Frankl', 'Man''s Search for Meaning'),
('Real wealth is not having to spend your time with people you don''t like.', 'Naval Ravikant', 'The Almanack of Naval Ravikant'),
('Time discovers truth.', 'Seneca', 'Letters from a Stoic'),
('Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.', 'Marcus Aurelius', 'Meditations'),
('Whoever fights monsters should see to it that in the process he does not become a monster.', 'Friedrich Nietzsche', 'Beyond Good and Evil'),
('Circumstances don''t make the man, they only reveal him to himself.', 'Epictetus', 'Discourses'),
('Life is fragile. We''re not guaranteed tomorrow, so give it everything you''ve got.', 'Tim Cook', 'Commencement');
